import type { ToolDefinition } from "./types.js";
import {
  ListEmailAccountsInput,
  ListReceivedEmailsInput,
  SendEmailInput,
  ListSentEmailsInput,
  ListThreadsInput,
  GetEmailAccountAnalyticsInput,
  AddEmailTagInput,
  RemoveEmailTagInput,
  AddToAudienceInput,
  RemoveFromAudienceInput,
  ListAudiencesInput,
  GetEmailInput,
  GetEmailRawInput,
  ReplyToEmailInput,
  ReplyAllToEmailInput,
  ForwardEmailInput,
  DeleteEmailInput,
  GetThreadInput,
  GetAttachmentInput,
  ListDraftsInput,
  GetDraftInput,
  CreateDraftInput,
  UpdateDraftInput,
  DeleteDraftInput,
  SendDraftInput,
  ListReplyStatusesInput,
  SetReplyStatusInput,
  GetCampaignAnalyticsInput,
  CreateCampaignInput,
  ListCampaignsInput,
  GetCampaignInput,
  DeleteCampaignInput,
  StartCampaignInput,
  PingInput,
} from "./schemas.js";

export const tools: ToolDefinition[] = [
  {
    name: "list_email_accounts",
    description: "List all registered email accounts with their details",
    parameters: ListEmailAccountsInput,
    annotations: { readOnlyHint: true },
  },
  {
    name: "list_received_emails",
    description: "List received emails in the INBOX with pagination and optional tag filtering",
    parameters: ListReceivedEmailsInput,
    annotations: { readOnlyHint: true },
  },
  {
    name: "send_email",
    description: "Send an email from a registered mailbox",
    parameters: SendEmailInput,
    annotations: { readOnlyHint: false },
  },
  {
    name: "list_sent_emails",
    description: "List sent emails with pagination and optional tag filtering",
    parameters: ListSentEmailsInput,
    annotations: { readOnlyHint: true },
  },
  {
    name: "list_threads",
    description: "Match received INBOX emails to sent emails by subject to find reply threads",
    parameters: ListThreadsInput,
    annotations: { readOnlyHint: true },
  },
  {
    name: "get_email_account_analytics",
    description: "Get analytics for an email account including sent counts, reply statuses, and rates",
    parameters: GetEmailAccountAnalyticsInput,
    annotations: { readOnlyHint: true },
  },
  {
    name: "add_email_tag",
    description: "Add an IMAP keyword/flag to an email message",
    parameters: AddEmailTagInput,
    annotations: { readOnlyHint: false },
  },
  {
    name: "remove_email_tag",
    description: "Remove an IMAP keyword/flag from an email message",
    parameters: RemoveEmailTagInput,
    annotations: { readOnlyHint: false },
  },
  {
    name: "add_to_audience",
    description: "Add a contact to audience segments across all mailboxes with optional metadata",
    parameters: AddToAudienceInput,
    annotations: { readOnlyHint: false },
  },
  {
    name: "remove_from_audience",
    description: "Remove a contact from audience segments across all mailboxes",
    parameters: RemoveFromAudienceInput,
    annotations: { readOnlyHint: false },
  },
  {
    name: "list_audiences",
    description: "List all audience segments with their contacts across all mailboxes",
    parameters: ListAudiencesInput,
    annotations: { readOnlyHint: true },
  },
  {
    name: "get_email",
    description: "Get full email details including body, headers, and attachment metadata",
    parameters: GetEmailInput,
    annotations: { readOnlyHint: true },
  },
  {
    name: "get_email_raw",
    description: "Get the raw RFC822 source of an email message",
    parameters: GetEmailRawInput,
    annotations: { readOnlyHint: true },
  },
  {
    name: "reply_to_email",
    description: "Reply to an email (single sender only)",
    parameters: ReplyToEmailInput,
    annotations: { readOnlyHint: false },
  },
  {
    name: "reply_all_to_email",
    description: "Reply to all recipients of an email",
    parameters: ReplyAllToEmailInput,
    annotations: { readOnlyHint: false },
  },
  {
    name: "forward_email",
    description: "Forward an email to new recipients with optional additional message",
    parameters: ForwardEmailInput,
    annotations: { readOnlyHint: false },
  },
  {
    name: "delete_email",
    description: "Delete an email message by UID",
    parameters: DeleteEmailInput,
    annotations: { readOnlyHint: false },
  },
  {
    name: "get_thread",
    description: "Get all emails in a thread by subject line matching across INBOX and Sent",
    parameters: GetThreadInput,
    annotations: { readOnlyHint: true },
  },
  {
    name: "get_attachment",
    description: "Download an email attachment by index as base64",
    parameters: GetAttachmentInput,
    annotations: { readOnlyHint: true },
  },
  {
    name: "list_drafts",
    description: "List draft emails with pagination",
    parameters: ListDraftsInput,
    annotations: { readOnlyHint: true },
  },
  {
    name: "get_draft",
    description: "Get full details of a draft email",
    parameters: GetDraftInput,
    annotations: { readOnlyHint: true },
  },
  {
    name: "create_draft",
    description: "Create a new draft email in the Drafts folder",
    parameters: CreateDraftInput,
    annotations: { readOnlyHint: false },
  },
  {
    name: "update_draft",
    description: "Update an existing draft by replacing it with new content",
    parameters: UpdateDraftInput,
    annotations: { readOnlyHint: false },
  },
  {
    name: "delete_draft",
    description: "Delete a draft email by UID",
    parameters: DeleteDraftInput,
    annotations: { readOnlyHint: false },
  },
  {
    name: "send_draft",
    description: "Send a draft email and remove it from Drafts",
    parameters: SendDraftInput,
    annotations: { readOnlyHint: false },
  },
  {
    name: "list_reply_statuses",
    description: "List all available reply status classifications with descriptions",
    parameters: ListReplyStatusesInput,
    annotations: { readOnlyHint: true },
  },
  {
    name: "set_reply_status",
    description: "Classify a received reply with a status tag, optionally tagging the matching sent email too",
    parameters: SetReplyStatusInput,
    annotations: { readOnlyHint: false },
  },
  {
    name: "get_campaign_analytics",
    description: "Get detailed analytics for a campaign including per-step and per-variant breakdowns",
    parameters: GetCampaignAnalyticsInput,
    annotations: { readOnlyHint: true },
  },
  {
    name: "create_campaign",
    description: "Create a new email campaign with A/B variant sequences targeting an audience segment",
    parameters: CreateCampaignInput,
    annotations: { readOnlyHint: false },
  },
  {
    name: "list_campaigns",
    description: "List all campaigns for an email account",
    parameters: ListCampaignsInput,
    annotations: { readOnlyHint: true },
  },
  {
    name: "get_campaign",
    description: "Get the full configuration of a campaign",
    parameters: GetCampaignInput,
    annotations: { readOnlyHint: true },
  },
  {
    name: "delete_campaign",
    description: "Delete a campaign configuration",
    parameters: DeleteCampaignInput,
    annotations: { readOnlyHint: false },
  },
  {
    name: "start_campaign",
    description: "Execute a campaign: send next pending step to each contact in the audience segment",
    parameters: StartCampaignInput,
    annotations: { readOnlyHint: false },
  },
  {
    name: "ping",
    description: "Health check — returns pong",
    parameters: PingInput,
    annotations: { readOnlyHint: true },
  },
];

export const toolsByName: Record<string, ToolDefinition> = Object.fromEntries(
  tools.map((t) => [t.name, t])
);
